---

- name: create Etherpad docker structure on server in /home/docker/etherpad
  file:
    name: /home/docker/etherpad
    state: directory
    owner: root
    group: root

## Install Etherpad docker
- name: copy Dockerfile
  copy:
    src: Dockerfile
    dest: /home/docker/etherpad/Dockerfile
    owner: root
    group: root
    mode: '0644'

- name: Install etherpad docker
  template:
    src: etherpad.yaml.j2
    dest: /home/docker/etherpad/docker-compose.yaml
    owner: root
    group: root
    mode: '0400'
  notify: 
    - start etherpad docker

## Backup Etherpad section
- name: Install Etherpad backup compose file
  template:
    src: backup.yaml.j2
    dest: /home/docker/backups/backup-etherpad.yaml
    owner: root
    group: root
    mode: '0400'
  when: inventory_hostname in groups['maintenance_contract']

- name: add cron job to run backup every day
  cron:
    name: backup etherpad
    minute: "33"
    hour: "3"
    job: /usr/local/bin/docker-compose -f /home/docker/backups/backup-etherpad.yaml run --rm backup_etherpad 
  when: inventory_hostname in groups['maintenance_contract']
